import {
  ClipboardCheck,
  MessageSquareWarning,
  Receipt,
  Send,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

import lipaPushImage from '../images/lipa push.jpeg';
import paymentsImage from '../images/payments.jpeg';
import receiptPreviewImage from '../images/receipt preview.jpeg';
import type { StaticImageData } from 'next/image';

/**
 * "From D-Labs" — products D-LABS builds and owns in-house.
 *
 * This is intentionally separate from `projects` (client work showcased on the
 * Projects page). Adding a product here only requires a new entry in
 * `products` plus a thin route at `app/from-d-labs/<slug>/page.tsx`.
 */
export type Product = {
  /** URL segment, also used for the dropdown href: /from-d-labs/<slug> */
  slug: string;
  name: string;
  /** Short line used in the navigation dropdown and hero headline */
  tagline: string;
  /** Meta description used for the page metadata */
  description: string;
  /** Short card summary, also reused in the navigation dropdown */
  summary: string;
  icon: LucideIcon;
  tags: string[];
  /** The everyday pain points the product answers */
  challenges: { title: string; text: string; icon: LucideIcon }[];
  /** Introductory narrative. Extend this array as the product page grows. */
  sections: { id: string; eyebrow: string; title: string; paragraphs: string[] }[];
  /** "What you get" — feature blocks, each with a product screenshot */
  features: {
    id: string;
    number: string;
    title: string;
    text: string;
    icon: LucideIcon;
    image: StaticImageData;
    imageAlt: string;
  }[];
  /** "How we do it" — the onboarding process, in order */
  process: { number: string; title: string; text: string }[];
  /** Pre-written contact messages used by the WhatsApp and Email actions */
  contact: { whatsappMessage: string; emailSubject: string; emailBody: string };
};

export const products: Product[] = [
  {
    slug: 'lipa',
    name: 'Lipa',
    tagline: 'M-Pesa payments your business can actually confirm.',
    description:
      'Lipa is a D-LABS product that lets businesses send M-Pesa STK Push requests, track payments in real time, and generate receipts for successful transactions.',
    summary: 'Send M-Pesa STK Push requests, track payments in real time, and generate receipts.',
    icon: Wallet,
    tags: ['M-Pesa', 'STK Push', 'Real-time tracking', 'Receipts', 'Built in-house'],
    challenges: [
      {
        title: 'Edited payment messages',
        text: 'Have your customers ever claimed they paid, only for you to discover the M-Pesa message was edited?',
        icon: MessageSquareWarning,
      },
      {
        title: 'Manual payment checks',
        text: "Or maybe you're tired of manually checking M-Pesa messages to confirm whether a payment actually went through.",
        icon: ClipboardCheck,
      },
    ],
    sections: [
      {
        id: 'meet-lipa',
        eyebrow: 'Introducing Lipa',
        title: 'Meet Lipa.',
        paragraphs: [
          'Lipa gives your business a simple way to send M-Pesa STK Push requests, track payments in real time, and generate receipts for successful transactions — all from one place.',
        ],
      },
    ],
    features: [
      {
        id: 'lipa-push',
        number: '01',
        title: 'Lipa Push',
        text: "Send an M-Pesa STK Push directly to your customer's phone. The customer enters their M-Pesa PIN and completes the payment without you having to manually confirm messages.",
        icon: Send,
        image: lipaPushImage,
        imageAlt: 'Lipa Push STK Push request screen on a phone',
      },
      {
        id: 'real-time-tracking',
        number: '02',
        title: 'Real-time payment tracking',
        text: 'Track payments as they happen from one dashboard. Quickly see whether a transaction is Paid, Pending, Failed, or Cancelled.',
        icon: Wallet,
        image: paymentsImage,
        imageAlt: 'Lipa dashboard showing real-time payment tracking',
      },
      {
        id: 'digital-receipts',
        number: '03',
        title: 'Digital receipts',
        text: 'Generate professional digital receipts for successful payments. Receipts can be downloaded as PDF, printed, or shared with the customer.',
        icon: Receipt,
        image: receiptPreviewImage,
        imageAlt: 'Preview of a digital receipt generated by Lipa',
      },
    ],
    process: [
      {
        number: '01',
        title: 'We help set up your payment account',
        text: 'We help you create and configure the required PayHero payment setup for your business.',
      },
      {
        number: '02',
        title: 'Payments go directly to your configured channel',
        text: 'Customer payments are processed through your configured M-Pesa payment channel.',
      },
      {
        number: '03',
        title: 'Lipa handles the payment flow',
        text: 'Lipa securely handles the payment request, tracks the transaction status, and validates the payment information.',
      },
      {
        number: '04',
        title: 'We configure Lipa for your business',
        text: 'We set up Lipa with your business details and make sure the payment flow is ready to use.',
      },
      {
        number: '05',
        title: 'We help you get started',
        text: 'We guide you through the setup and help verify that your payment flow is working correctly.',
      },
    ],
    contact: {
      whatsappMessage:
        "Hi D-Labs 👋, I’m interested in Lipa and I’d like to learn more about getting it for my business.",
      emailSubject: 'Interested in Lipa',
      emailBody: "Hi D-Labs,\n\nI’m interested in Lipa and I’d like to learn more about getting it for my business.\n\nThank you.",
    },
  },
];

export function getProduct(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}

export function getProductHref(product: Pick<Product, 'slug'>): string {
  return `/from-d-labs/${product.slug}`;
}

export type FromDLabsNavItem = {
  label: string;
  href: string;
  description: string;
};
